//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flights
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ID { get; set; }
        public string TicketCode { get; set; }
        public int TripID { get; set; }
        public string Class { get; set; }
        public int Place { get; set; }
        public int CustomerID { get; set; }
        public decimal Cost { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Trip Trip { get; set; }
    }
}
