//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bus_route_automation_system
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBase3 : DbContext
    {
        private static DataBase3 _context;

        public static DataBase3 GetContext()
        {
            if (_context == null)
                _context = new DataBase3();
            return _context;
        }
        public DataBase3()
            : base("name=DataBase3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Driver> Driver { get; set; }
        public virtual DbSet<DriverLicense> DriverLicense { get; set; }
        public virtual DbSet<DriverVoyage> DriverVoyage { get; set; }
        public virtual DbSet<Route> Route { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Voyage> Voyage { get; set; }
    }
}
