//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libraly
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBase2 : DbContext
    {
        private static DataBase2 _context;

        public static DataBase2 GetContext()
        {
            if (_context == null)
                _context = new DataBase2();
            return _context;
        }

        public DataBase2()
            : base("name=DataBase2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Book { get; set; }
        public virtual DbSet<BookGenre> BookGenre { get; set; }
        public virtual DbSet<Genre> Genre { get; set; }
        public virtual DbSet<Reader> Reader { get; set; }
        public virtual DbSet<ReaderBook> ReaderBook { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
