//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automation_Of_Bus_Routes
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverVoyage
    {
        public int ID { get; set; }
        public int DriverID { get; set; }
        public int VoyageID { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Voyage Voyage { get; set; }
    }
}
